[build-system]
requires = ["scikit_build_core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "neo_dsp"
version = "0.1.0"
requires-python = ">=3.7"

[tool.scikit-build]
cmake.source-dir = "python"
